version: '3'

services:
  app:
    image: node:12.16.3-alpine
    tty: true
    working_dir: /app
    volumes:
      - .:/app
    command: >
      sh -c "
      npm install
      && npm run start
      "
